name: BlitzSG
version: 1.0
main: me.syesstyles.blitz.BlitzSG
author: Syes, Hardstyles
description: BlitzSG Plugin
commands:
  nick:
    description: lol
  world:
    description: lol
  bsg:
    description: lol
  fw:
    description: lol
  acban:
    description: lol
  unban:
    description: lol
  debug:
    description: lol



