name: BlitzSG
version: 1.0
main: me.syesstyles.blitz.BlitzSG
depend: [KarhuAPI]
author: Syes, Hardstyles
description: BlitzSG Plugin

commands:
  fw:
    description: lol
  acban:
    description: lol
  unban:
    description: lol
  taunt:
    description: lol
  wtfmap:
    description: lol
  startdm:
    description: lol

