name: NoctasBuild
version: 1.0
main: org.example.SpigotServer.SpigotServer
commands:
  rank:
    description: Your description
    usage: /<command>
    permission: yourplugin.yourcommandpermission
  day:
    description: Set time to day (client side)
    usage: /<command>
    permission: noctas.commands.time
  sunset:
    description: Set time to sunset (client side)
    usage: /<command>
    permission: noctas.commands.time
  night:
    description: Set time to night (client side)
    usage: /<command>
    permission: noctas.commands.time
  resettime:
    description: Use server time
    usage: /<command>
    permission: noctas.commands.time
  tp:
    description: Use server time
    usage: /<command>
    aliases: [teleport, goto]
    permission: noctas.commands.staff
  gmc:
    description: Change gamemode
    usage: /<command>
    permission: noctas.commands.gamemode
  gms:
    description: Change gamemode
    usage: /<command>
    permission: noctas.commands.gamemode
  gmsp:
    description: Change gamemode
    usage: /<command>
    permission: noctas.commands.gamemode
  gma:
    description: Change gamemode
    usage: /<command>
    permission: noctas.commands.gamemode
  ping:
    description: ping
    usage: /<command>
    permission: noctas.commands.ping