name: BlitzSG
version: 1.0
main: me.syesstyles.blitz.BlitzSG
author: Syes
description: BlitzSG Plugin
commands:
  bsg:
    description: main plugin command
    aliases: [speeduhc]
  world:
    description: world command lol