name: BlitzSG
version: 1.0
main: me.syesstyles.blitz.BlitzSG
author: Syes
description: BlitzSG Plugin
commands:
  bsg:
    description: main plugin command
    aliases: [blitz]
  world:
    description: world command lol
  nick:
    description: world command lol
  fw:
    description: world command lol
    aliases: [firework]
